image: frolvlad/alpine-glibc:latest

before_script:
  - apk add maven python3 openjdk17 -q
  - . source-pipeline.sh

stages:
  - compile
  - test

variables:
  # Arguments to pass in the Maven CLI.
  MAVEN_CLI_OPTS: "--no-transfer-progress"
  # Arguments to pass to Maven tasks.
  MAVEN_OPTS: ""

cache:
  paths:
    - target/

compile:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS compile $MAVEN_OPTS

test:
  stage: test
  script:
    - . arm-env.sh install
    - . arm-test.sh
    - mvn $MAVEN_CLI_OPTS verify $MAVEN_OPTS
  # Run jacoco regardless of if the build failed or succeded,
  # so that we can see the coverage check.
  after_script:
    # See [Jacoco] p155.
    # Also see the gitlab wiki for why we do this.
    - mvn jacoco:restore-instrumented-classes jacoco:report
  artifacts:
    when: always
    expose_as: 'JaCoCo couverture de code'
    paths:
      - target/site/
    expire_in: 1 week

